ARG BASE_IMAGE=koide3/glim_ros2:humble
FROM $BASE_IMAGE

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    ros-humble-pcl-ros \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY glim_ext /root/ros2_ws/src/glim_ext
WORKDIR /root/ros2_ws
RUN . /opt/ros/humble/setup.sh && colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Release

CMD ["bash"]
